on:
 workflow_dispatch:
 push:
  paths:
    - 'src/**'
  branches: [ main ]
 pull_request:
  branches: [ main ]

name: "Build project"

env:
 CARGO_TERM_COLOR: always
 CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
 build_and_test:
  name: DownOnSpot
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   - run: sudo apt install -y libasound2-dev libmp3lame-dev  
   - uses: webfactory/ssh-agent@v0.5.3
     with:
      ssh-private-key: ${{ secrets.FREE_LIBRESPOT_PRIVATE_KEY }}
   - uses: actions-rs/toolchain@v1
     with:
      override: true
      toolchain: nightly
   - run: cargo build --release --all-features